[package]
name = "asciigraphix-ssh"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
crossterm = "0.29.0"
rand = "0.9.2"
ratatui = "0.29.0"
russh = "0.54.6"
ssh-key = "0.6.7"
tokio = "1.48.0"
