[package]
name = "asciigraphix-tui"
version = "0.1.0"
edition = "2024"

[lib]
name = "asciigraphix_tui"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
asciigraphix-core = {path = "../asciigraphix-core/"}
figlet-rs = "0.1.5"
